language: python
os:
- linux
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install flake8
install:
- pip install .
stages:
- lint
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120
script: echo "Success!"
deploy:
  provider: pypi
  user: __token__
  password:
    secure: rtZ3EP+MLsCxJfUjtGRA2E7KvM3dQShYrjUXTX1PfJl0kZ0JBvGYLhiG2eRS6iqMSb6aLLty8xJu3AsS3Dyb8YIrFkIFosZ2dZNMIQyfm/hBcEpTkmDhr2SvPtSAuQ8UKQ0mtnDM0CG8mKzp+7ocxloMdjyBWRP4kzMgmEoXkjHJ0R0duV4GrjGjsZ2Fytl2ElrSJF07oWvHm95vQEKjbx0uUlPAQxINaYLN5Z8z73u8qSkU721Tp6iGsdUgHv5kLCfupsU4vQHylfVHB+wqnrf0sdcOXzjUY6DfBrzji2R9Se51TsjWawhaFM2UwoA0HlnDgbJR5GB7sJOOnIMEuIn3WBY5yxo5mnYxoGntPHyyaNh+Wjrz6nuQmPn9Nu0UvMLXRAW3US0pYQet2+bkXrhnmhx/0EfblyWpXxQRrPtbyoHj/VNLteqGy+FiqvKVE9ucnuhxBb2qmCiAxpCSNaEN4wNU9gt1Ebq1ejUnRavLgN3zIU1fEvpQmznzzowNTLmXF5C4183SXEGOmsJDgArCFKFeWD8QA8D/NQR1cCQIST0ZJiLjfDq+mVBnF1HPIoFdMQxxEtxj2+X9BM4y7kWFMHGsx0oZQnp72XKvGh8/FAUaxB34mb8Y0xTF8xm4cn4bJ2rX+d7ODAnRbry3a9VjOVgQVpVuYnIyk9wWFQU=
  on:
    tags: true
  skip_existing: true
